spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:db/database.xml
    contexts: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batch_compilation
    username: user
    password: password
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: validate
      
  batch:
    job:      enabled: true

file:
  csv-separator: รง
  extension: .dat
  inputdir: file:${user.home}/data/in
  output-path:  ${user.home}/data/out/batch-compilation.done.dat